### ISSUE TITLE
Help, I did not find any executable file and I got an error when I opened and ran this project with Godot4.

### ISSUE THREAD

**Issue by DCLCYC** [Astral-Sheep/GodotHub#2]
### Discussed in https://github.com/Astral-Sheep/GodotHub/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **DCLCYC** January 10, 2024</sup>
Hello, I did not find any executable file in your project. When I downloaded the project and opened it with Godot4 to export the executable file myself, I got the following error: 
Error loading: main.tscn due to Loadfailed due tomissing dependencies: res://scenes/debug/debugger.tscn
![image](https://github.com/Astral-Sheep/GodotHub/assets/43945278/41e6d2ae-48aa-4012-b439-513e436f115a)
Execution error as follows: 
![image](https://github.com/Astral-Sheep/GodotHub/assets/43945278/e5fdeaa8-c667-48ce-ad5e-4a205ca84740)
Could you help me solve this problem when you are free?</div>

**Comment by Astral-Sheep** [comment]
Hello. Did you check the releases for the executable ? I just checked that the .zip files aren't empty, and the executable seems to work in them.
Which version of godot are you using exactly ? I'm working with Godot 4.0.4 mono. Do you have C# support installed for your version ?

**Comment by DCLCYC** [comment]
> Hello. Did you check the releases to get the executable ? I just checked that the .zip files aren't empty, and the executable seems to work in them. Which version of godot are you using exactly ? I'm working with Godot 4.0.4 mono. Do you have C# support installed for your version ?

releases? oh, I see the zip file, I rarely use github, I thought only the following form has a usable release package, when I saw only tags displayed at the releases, I thought there was no executable file, this is my problem, I’m sorry to bother you because of this. 
![image](https://github.com/Astral-Sheep/GodotHub/assets/43945278/2d075e1e-317a-48bc-af76-373ac32f9b1d)

Also, I saw you mentioned using Godot4 to open the project folder, so I downloaded Godot4.0 and Godot4.1.1, they both have Mono support, I switched from learning Unity to Godot, so I’m not using GdScript language, the local language support should be no problem, in the error message when opening the project, it said that scenes/debug/debugger.tscn was not found when loading main.tscn, but there is no scenes/debug folder in your project folder, is it because of this?

**Comment by Astral-Sheep** [comment]
Don't worry, we all needed to learn how to use github at some point.

For the project part, if you cloned the repository from the last commit, since it isn't stable at all it is expected to have some bugs. I am currently implementing multi-processing for some other features, and the current commit is only a part of the actual state of the project.
I recommend to **download the** `Source code (zip)` **file in the last release** to have a (mostly) stable project. The source code should work with Godot 4.0.x, but I don't know how it behaves with other versions of the engine.
![image](https://github.com/Astral-Sheep/GodotHub/assets/109028693/4cb0abc4-2528-4230-9ff1-6b0885fdaed3)

**Comment by DCLCYC** [comment]
> Don't worry, we all needed to learn how to use github at some point.
> 
> For the project part, if you cloned the repository from the last commit, since it isn't stable at all it is expected to have some bugs. I am currently implementing multi-processing for some other features, and the current commit is only a part of the actual state of the project. I recommend to **download the** `Source code (zip)` **file in the last release** to have a (mostly) stable project. The source code should work with Godot 4.0.x, but I don't know how it behaves with other versions of the engine. ![image](https://private-user-images.githubusercontent.com/109028693/295675107-4cb0abc4-2528-4230-9ff1-6b0885fdaed3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5Mzc0OTEsIm5iZiI6MTcwNDkzNzE5MSwicGF0aCI6Ii8xMDkwMjg2OTMvMjk1Njc1MTA3LTRjYjBhYmM0LTI1MjgtNDIzMC05ZmYxLTZiMDg4NWZkYWVkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwMTM5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzYwODdjZGEwNDRkNDU4YjA0OTdjNmI3ZDRjOGJjMzRhYjc0MDFhYjA0Njc0OTM4NmYwMjIzNzg2ZGQyMGRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tojAkNi1C5bE5wiDDlAVDIaDAKL8pR9nzAuWHLC_Aag)
> 
> Edit: if you are on Linux or Mac, I don't know how the project behaves since I never tested it on these OS.

Thank you for your reply, I have tried to download GodotHub_v0.1.2_win64.zip and the source code to my local and found the exported executable file (I am using windows operating system), although it still has some problems, such as the first time launching the software showing a null reference problem, the setting page cannot switch to other disks, can only set the default folder in C drive, cannot create a new project, the installs page cannot get the installation version information, etc., but I am still very grateful for your open source work, this is very helpful to me, I will also study your open source source code through research, thank you again for your open source work. I originally wanted to say that I look forward to your future submission, but this is ultimately your open source project, even if it is abandoned and no longer submitted or deleted it is your freedom, saying this might put some pressure on you, you can act freely according to your will. Wish you a happy life.

**Comment by Astral-Sheep** [comment]
Thank you for your kind words. Most of the bugs you talked about here are already known and I'm planning to fix them (the new project creation is done (just missing the icon), the disk one is on the way too (you can still set the path manually to change your disk)).
Since it is a side project I don't plan to put pressure on myself, that's why I'm not very active these days, but I still want to have a full release at some point to help people like you who are switching from Unity to Godot.
I expect that you will have fun learning Godot.

**Comment by Astral-Sheep** [comment]
By the way, does it help with some errors if you delete the content of the GodotHub folder in your RoamingAppdata folder ?

**Comment by DCLCYC** [comment]
> By the way, does it help with some errors if you delete the content of the GodotHub folder in your RoamingAppdata folder ?

Yes, I don’t want to put any pressure on you, you can do whatever you want to do, Godot is a very interesting engine, I also joined some Godot contributors created chat groups and learned a lot of things. Regarding testing, I deleted the Godothub folder under  %AppData%, it seems that the Releases page on Installs can show the specific version list of Godot and clicked download, I remember it very clearly, yesterday when using this software, the list under Installs -> Releases did not have any content, now it has, but even if I add a download task and can see the specific download task in the left side download task list after clicking on the download icon, but this download task seems to have no use at all, its progress bar will not change, after a while, this download task disappears and there is no specific Godot version installed and displayed on the Installs interface, I hope this helps you, because I currently have other work so I may not be able to conduct more detailed testing about this point I am very sorry.

**Comment by Astral-Sheep** [comment]
Thanks for your feedback, it's already a lot. I think it's a visual bug that I fixed in one of the last commits, but I'll check it just to be sure.
